import { useStore } from '../store/useStore';
import { SEQUENCE_DURATION } from '../theatre/core';

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Read scroll keyframes directly from Zustand — authoritative source. */
function getScrollKeyframes() {
    return useStore.getState().scrollKeyframes;
}

/**
 * Inline JS snippet embedded in exported HTML.
 * evalCurve(keyframes, t, sequenceDuration) → 0..1
 * Supports linear / easeIn / easeOut / easeInOut / step and bezier handles.
 */
const EVAL_CURVE_JS = `
function _applyEasing(alpha, easing) {
  if (easing === 'easeIn')    return alpha * alpha * alpha;
  if (easing === 'easeOut')   { var t = 1 - alpha; return 1 - t * t * t; }
  if (easing === 'easeInOut') return alpha < 0.5 ? 4 * Math.pow(alpha, 3) : 1 - Math.pow(-2 * alpha + 2, 3) / 2;
  return alpha;
}
function _cubicBez(t, p0, p1, p2, p3) {
  var mt = 1 - t;
  return mt*mt*mt*p0 + 3*mt*mt*t*p1 + 3*mt*t*t*p2 + t*t*t*p3;
}
function evalCurve(keyframes, t, sequenceDuration) {
  if (!keyframes.length) return t / sequenceDuration;
  if (t <= keyframes[0].time) return keyframes[0].value;
  if (t >= keyframes[keyframes.length - 1].time) return keyframes[keyframes.length - 1].value;
  for (var i = 0; i < keyframes.length - 1; i++) {
    var a = keyframes[i], b = keyframes[i + 1];
    if (t >= a.time && t <= b.time) {
      if (a.easing === 'step') return a.value;
      var alpha = (t - a.time) / (b.time - a.time);
      if (a.handleOut || b.handleIn) {
        var p1v = a.value + (a.handleOut ? a.handleOut.dv : 0);
        var p2v = b.value + (b.handleIn  ? b.handleIn.dv  : 0);
        return _cubicBez(alpha, a.value, p1v, p2v, b.value);
      }
      return a.value + _applyEasing(alpha, a.easing || 'linear') * (b.value - a.value);
    }
  }
  return 0;
}`.trim();

/** Trigger a file download in the browser. */
function downloadFile(filename: string, content: string, mime = 'text/html') {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

// ─── Story 5.2 — Particle Hero HTML ──────────────────────────────────────────

export function exportParticleHeroHtml() {
    const keyframes = getScrollKeyframes();

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Scroll Hero — Particle Scene</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { height: 500vh; background: #0a0a0f; font-family: sans-serif; }

    /* ── Sticky hero container ───────────────────────────────────────────── */
    .hero {
      position: sticky;
      top: 0;
      width: 100%;
      height: 100vh;
      overflow: hidden;
      background: #0a0a0f;
    }

    /* ── Placeholder canvas — replace with your Three.js / R3F scene ─────── */
    canvas { display: block; width: 100%; height: 100%; }

    .overlay {
      position: absolute;
      inset: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      pointer-events: none;
    }
    .progress-ring {
      width: 120px; height: 120px;
      border-radius: 50%;
      border: 2px solid rgba(168,85,247,0.3);
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 13px;
      color: rgba(168,85,247,0.8);
      font-variant-numeric: tabular-nums;
    }
  </style>
</head>
<body>

  <!--
    ┌──────────────────────────────────────────────────────────────────────────┐
    │  SCROLL HERO — Particle Scene Export                                     │
    │  Generated by Scroll Hero Editor                                         │
    │                                                                          │
    │  INTEGRATION GUIDE                                                       │
    │  1. Replace <canvas id="hero-canvas"> with your Three.js / R3F scene.   │
    │  2. Your scene should expose a setProgress(p: 0..1) function.           │
    │  3. The onUpdate callback already calls setProgress with the curve value.│
    │  4. The KEYFRAMES array below bakes your scroll automation curves.        │
    └──────────────────────────────────────────────────────────────────────────┘
  -->

  <div class="hero">
    <!-- Replace this canvas with your Three.js mount point -->
    <canvas id="hero-canvas"></canvas>

    <div class="overlay">
      <div class="progress-ring" id="progress-display">0.00</div>
    </div>
  </div>

  <!-- GSAP + ScrollTrigger -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>

  <script>
    // ── Baked curve data from Theatre.js ──────────────────────────────────
    const SEQUENCE_DURATION = ${SEQUENCE_DURATION};
    const KEYFRAMES = ${JSON.stringify(keyframes, null, 4)};

    // ── Curve interpolation (linear) ──────────────────────────────────────
    ${EVAL_CURVE_JS}

    // ── Placeholder canvas particle animation ────────────────────────────
    //    DELETE everything in this block once you integrate your own scene.
    (function initPlaceholder() {
      const canvas = document.getElementById('hero-canvas');
      const ctx = canvas.getContext('2d');
      const COUNT = 300;
      const particles = Array.from({ length: COUNT }, () => ({
        x: Math.random(), y: Math.random(),
        vx: (Math.random() - 0.5) * 0.002,
        vy: (Math.random() - 0.5) * 0.002,
        r: Math.random() * 2 + 0.5,
      }));

      function resize() { canvas.width = canvas.offsetWidth; canvas.height = canvas.offsetHeight; }
      window.addEventListener('resize', resize);
      resize();

      let currentProgress = 0;

      // Expose so the ScrollTrigger hook below can drive it
      window.setProgress = function(p) { currentProgress = p; };

      function draw() {
        requestAnimationFrame(draw);
        const W = canvas.width, H = canvas.height;
        ctx.fillStyle = 'rgba(10,10,15,0.15)';
        ctx.fillRect(0, 0, W, H);

        const hue = 270 + currentProgress * 120; // purple → teal as scroll progresses
        particles.forEach(p => {
          p.x = (p.x + p.vx * (0.5 + currentProgress * 2) + 1) % 1;
          p.y = (p.y + p.vy * (0.5 + currentProgress * 2) + 1) % 1;
          ctx.beginPath();
          ctx.arc(p.x * W, p.y * H, p.r * (1 + currentProgress), 0, Math.PI * 2);
          ctx.fillStyle = \`hsla(\${hue}, 80%, 70%, \${0.3 + currentProgress * 0.7})\`;
          ctx.fill();
        });
      }
      draw();
    })();

    // ── ScrollTrigger → curve → scene ────────────────────────────────────
    gsap.registerPlugin(ScrollTrigger);

    const display = document.getElementById('progress-display');

    ScrollTrigger.create({
      start: 'top top',
      end: 'bottom bottom',
      onUpdate(self) {
        const t = self.progress * SEQUENCE_DURATION;
        const p = evalCurve(KEYFRAMES, t, SEQUENCE_DURATION);

        // Drive your scene here:
        if (typeof window.setProgress === 'function') window.setProgress(p);

        if (display) display.textContent = p.toFixed(2);
      },
    });
  </script>

</body>
</html>`;

    downloadFile('scroll-hero-particle.html', html);
}

// ─── Story 5.3 — Frame Sequence Hero HTML ────────────────────────────────────

export async function exportFrameSequenceHeroHtml(mp4BlobUrl: string, mp4Name: string) {
    const keyframes = getScrollKeyframes();

    // Convert the blob URL to base64
    const response = await fetch(mp4BlobUrl);
    const buffer = await response.arrayBuffer();
    const bytes = new Uint8Array(buffer);
    let binary = '';
    // Chunk to avoid stack overflow on large files
    const CHUNK = 8192;
    for (let i = 0; i < bytes.length; i += CHUNK) {
        binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
    }
    const base64 = btoa(binary);
    const dataUri = `data:video/mp4;base64,${base64}`;

    const sizeMB = (buffer.byteLength / 1024 / 1024).toFixed(1);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Scroll Hero — ${mp4Name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { height: 500vh; background: #0a0a0f; }

    .hero {
      position: sticky;
      top: 0;
      width: 100%;
      height: 100vh;
      overflow: hidden;
    }
    video {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
  </style>
</head>
<body>

  <!--
    ┌──────────────────────────────────────────────────────────────────────────┐
    │  SCROLL HERO — Frame Sequence Export                                     │
    │  Source: ${mp4Name} (${sizeMB} MB embedded as base64)${''.padEnd(Math.max(0, 43 - mp4Name.length - sizeMB.length))} │
    │  Generated by Scroll Hero Editor                                         │
    │                                                                          │
    │  The video is driven by your baked scroll automation curve.             │
    │  Scroll the page to play the animation.                                  │
    └──────────────────────────────────────────────────────────────────────────┘
  -->

  <!-- ScrollyVideo container — drives video via setVideoPercentage() -->
  <div class="hero" id="scrolly-container">
    <video id="hero-video" muted playsinline preload="auto"
      src="${dataUri}">
    </video>
  </div>

  <!-- ScrollyVideo.js — smooth scroll-driven video seeking (FR8b) -->
  <script src="https://cdn.jsdelivr.net/npm/scrollyvideo@2/dist/scrollyvideo.js"></script>
  <!-- GSAP + ScrollTrigger -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>

  <script>
    // ── Baked scroll automation curve ─────────────────────────────────────
    const SEQUENCE_DURATION = ${SEQUENCE_DURATION};
    const KEYFRAMES = ${JSON.stringify(keyframes, null, 4)};

    // ── Curve interpolation (easing + bezier handle support) ──────────────
    ${EVAL_CURVE_JS}

    // ── ScrollyVideo instance (full:false = manual control via setVideoPercentage) ──
    var scrollyVideo = new ScrollyVideo({
      scrollyVideoContainer: document.getElementById('scrolly-container'),
      src: document.getElementById('hero-video').src,
      full: false,
      sticky: false,
      cover: true,
    });

    // ── GSAP ScrollTrigger → baked curve → ScrollyVideo ──────────────────
    gsap.registerPlugin(ScrollTrigger);

    ScrollTrigger.create({
      start: 'top top',
      end: 'bottom bottom',
      onUpdate: function(self) {
        var t = self.progress * SEQUENCE_DURATION;
        var p = evalCurve(KEYFRAMES, t, SEQUENCE_DURATION);
        scrollyVideo.setVideoPercentage(p, { ms: 80 });
      },
    });
  </script>

</body>
</html>`;

    downloadFile(`scroll-hero-${mp4Name.replace(/\.mp4$/i, '')}.html`, html);
}

// ─── Story 5.4 — Export Curves JSON (FR25) ───────────────────────────────────

/** Export the scroll automation curve as a standalone curves.json file. */
export function exportCurvesJson() {
    const keyframes = getScrollKeyframes();
    const data = JSON.stringify({ sequenceDuration: SEQUENCE_DURATION, keyframes }, null, 2);
    downloadFile('scroll-curves.json', data, 'application/json');
}
