import studio from '@theatre/studio';
import { SEQUENCE_DURATION } from '../theatre/core';

// ─── Types ────────────────────────────────────────────────────────────────────

interface Keyframe {
    position: number; // seconds 0..SEQUENCE_DURATION
    value: number;    // 0..1
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Extract position keyframes from a Theatre.js save-file blob. */
function extractScrollKeyframes(saveFile: unknown): Keyframe[] {
    try {
        const sf = saveFile as Record<string, unknown>;
        const sheet = (sf.sheetsById as Record<string, unknown>)?.['Main Sequence'] as Record<string, unknown>;
        const byObj = (sheet?.sequence as Record<string, unknown>)?.tracksByObject as Record<string, unknown>;
        const scrollControls = byObj?.['Scroll Controls'] as Record<string, unknown>;
        const trackData = scrollControls?.trackData as Record<string, { keyframes: Keyframe[] }>;
        if (!trackData) return [];
        // find the position track (first track with numeric values)
        const track = Object.values(trackData)[0];
        return (track?.keyframes ?? []).map((kf) => ({ position: kf.position, value: kf.value }));
    } catch {
        return [];
    }
}

/** Inline JS snippet: evalCurve(keyframes, t) → 0..1 */
const EVAL_CURVE_JS = `
function evalCurve(keyframes, t, sequenceDuration) {
  if (!keyframes.length) return t / sequenceDuration;
  if (t <= keyframes[0].position) return keyframes[0].value;
  if (t >= keyframes[keyframes.length - 1].position) return keyframes[keyframes.length - 1].value;
  for (let i = 0; i < keyframes.length - 1; i++) {
    const a = keyframes[i], b = keyframes[i + 1];
    if (t >= a.position && t <= b.position) {
      const u = (t - a.position) / (b.position - a.position);
      return a.value + (b.value - a.value) * u;
    }
  }
  return 0;
}`.trim();

/** Trigger a file download in the browser. */
function downloadFile(filename: string, content: string, mime = 'text/html') {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

// ─── Story 5.2 — Particle Hero HTML ──────────────────────────────────────────

export function exportParticleHeroHtml() {
    const saveFile = studio.createContentOfSaveFile('Scroll Hero Editor');
    const keyframes = extractScrollKeyframes(saveFile);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Scroll Hero — Particle Scene</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { height: 500vh; background: #0a0a0f; font-family: sans-serif; }

    /* ── Sticky hero container ───────────────────────────────────────────── */
    .hero {
      position: sticky;
      top: 0;
      width: 100%;
      height: 100vh;
      overflow: hidden;
      background: #0a0a0f;
    }

    /* ── Placeholder canvas — replace with your Three.js / R3F scene ─────── */
    canvas { display: block; width: 100%; height: 100%; }

    .overlay {
      position: absolute;
      inset: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      pointer-events: none;
    }
    .progress-ring {
      width: 120px; height: 120px;
      border-radius: 50%;
      border: 2px solid rgba(168,85,247,0.3);
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 13px;
      color: rgba(168,85,247,0.8);
      font-variant-numeric: tabular-nums;
    }
  </style>
</head>
<body>

  <!--
    ┌──────────────────────────────────────────────────────────────────────────┐
    │  SCROLL HERO — Particle Scene Export                                     │
    │  Generated by Scroll Hero Editor                                         │
    │                                                                          │
    │  INTEGRATION GUIDE                                                       │
    │  1. Replace <canvas id="hero-canvas"> with your Three.js / R3F scene.   │
    │  2. Your scene should expose a setProgress(p: 0..1) function.           │
    │  3. The onUpdate callback already calls setProgress with the curve value.│
    │  4. The KEYFRAMES array below bakes your exact Theatre.js curves.        │
    └──────────────────────────────────────────────────────────────────────────┘
  -->

  <div class="hero">
    <!-- Replace this canvas with your Three.js mount point -->
    <canvas id="hero-canvas"></canvas>

    <div class="overlay">
      <div class="progress-ring" id="progress-display">0.00</div>
    </div>
  </div>

  <!-- GSAP + ScrollTrigger -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>

  <script>
    // ── Baked curve data from Theatre.js ──────────────────────────────────
    const SEQUENCE_DURATION = ${SEQUENCE_DURATION};
    const KEYFRAMES = ${JSON.stringify(keyframes, null, 4)};

    // ── Curve interpolation (linear) ──────────────────────────────────────
    ${EVAL_CURVE_JS}

    // ── Placeholder canvas particle animation ────────────────────────────
    //    DELETE everything in this block once you integrate your own scene.
    (function initPlaceholder() {
      const canvas = document.getElementById('hero-canvas');
      const ctx = canvas.getContext('2d');
      const COUNT = 300;
      const particles = Array.from({ length: COUNT }, () => ({
        x: Math.random(), y: Math.random(),
        vx: (Math.random() - 0.5) * 0.002,
        vy: (Math.random() - 0.5) * 0.002,
        r: Math.random() * 2 + 0.5,
      }));

      function resize() { canvas.width = canvas.offsetWidth; canvas.height = canvas.offsetHeight; }
      window.addEventListener('resize', resize);
      resize();

      let currentProgress = 0;

      // Expose so the ScrollTrigger hook below can drive it
      window.setProgress = function(p) { currentProgress = p; };

      function draw() {
        requestAnimationFrame(draw);
        const W = canvas.width, H = canvas.height;
        ctx.fillStyle = 'rgba(10,10,15,0.15)';
        ctx.fillRect(0, 0, W, H);

        const hue = 270 + currentProgress * 120; // purple → teal as scroll progresses
        particles.forEach(p => {
          p.x = (p.x + p.vx * (0.5 + currentProgress * 2) + 1) % 1;
          p.y = (p.y + p.vy * (0.5 + currentProgress * 2) + 1) % 1;
          ctx.beginPath();
          ctx.arc(p.x * W, p.y * H, p.r * (1 + currentProgress), 0, Math.PI * 2);
          ctx.fillStyle = \`hsla(\${hue}, 80%, 70%, \${0.3 + currentProgress * 0.7})\`;
          ctx.fill();
        });
      }
      draw();
    })();

    // ── ScrollTrigger → curve → scene ────────────────────────────────────
    gsap.registerPlugin(ScrollTrigger);

    const display = document.getElementById('progress-display');

    ScrollTrigger.create({
      start: 'top top',
      end: 'bottom bottom',
      onUpdate(self) {
        const t = self.progress * SEQUENCE_DURATION;
        const p = evalCurve(KEYFRAMES, t, SEQUENCE_DURATION);

        // Drive your scene here:
        if (typeof window.setProgress === 'function') window.setProgress(p);

        if (display) display.textContent = p.toFixed(2);
      },
    });
  </script>

</body>
</html>`;

    downloadFile('scroll-hero-particle.html', html);
}

// ─── Story 5.3 — Frame Sequence Hero HTML ────────────────────────────────────

export async function exportFrameSequenceHeroHtml(mp4BlobUrl: string, mp4Name: string) {
    const saveFile = studio.createContentOfSaveFile('Scroll Hero Editor');
    const keyframes = extractScrollKeyframes(saveFile);

    // Convert the blob URL to base64
    const response = await fetch(mp4BlobUrl);
    const buffer = await response.arrayBuffer();
    const bytes = new Uint8Array(buffer);
    let binary = '';
    // Chunk to avoid stack overflow on large files
    const CHUNK = 8192;
    for (let i = 0; i < bytes.length; i += CHUNK) {
        binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
    }
    const base64 = btoa(binary);
    const dataUri = `data:video/mp4;base64,${base64}`;

    const sizeMB = (buffer.byteLength / 1024 / 1024).toFixed(1);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Scroll Hero — ${mp4Name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { height: 500vh; background: #0a0a0f; }

    .hero {
      position: sticky;
      top: 0;
      width: 100%;
      height: 100vh;
      overflow: hidden;
    }
    video {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
  </style>
</head>
<body>

  <!--
    ┌──────────────────────────────────────────────────────────────────────────┐
    │  SCROLL HERO — Frame Sequence Export                                     │
    │  Source: ${mp4Name} (${sizeMB} MB embedded as base64)${''.padEnd(Math.max(0, 43 - mp4Name.length - sizeMB.length))} │
    │  Generated by Scroll Hero Editor                                         │
    │                                                                          │
    │  The video is driven by your baked Theatre.js curve.                    │
    │  Scroll the page to play the animation.                                  │
    └──────────────────────────────────────────────────────────────────────────┘
  -->

  <div class="hero">
    <video id="hero-video" muted playsinline preload="auto"
      src="${dataUri}">
    </video>
  </div>

  <!-- GSAP + ScrollTrigger -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>

  <script>
    // ── Baked curve data from Theatre.js ──────────────────────────────────
    const SEQUENCE_DURATION = ${SEQUENCE_DURATION};
    const KEYFRAMES = ${JSON.stringify(keyframes, null, 4)};

    // ── Curve interpolation (linear) ──────────────────────────────────────
    ${EVAL_CURVE_JS}

    // ── ScrollTrigger → curve → video scrub ──────────────────────────────
    gsap.registerPlugin(ScrollTrigger);

    const video = document.getElementById('hero-video');

    // Wait for metadata so video.duration is available
    video.addEventListener('loadedmetadata', () => {
      ScrollTrigger.create({
        start: 'top top',
        end: 'bottom bottom',
        onUpdate(self) {
          const t = self.progress * SEQUENCE_DURATION;
          const p = evalCurve(KEYFRAMES, t, SEQUENCE_DURATION);
          video.currentTime = p * video.duration;
        },
      });
    });
  </script>

</body>
</html>`;

    downloadFile(`scroll-hero-${mp4Name.replace(/\.mp4$/i, '')}.html`, html);
}
